# Define un mensaje con ordenes para el robot
# Las posibles órdenes incluyen:
#  * Parar o arrancar publishers
#  * Enceder o apagar leds
#  * Configurar el modo de accion de los motores
# Ver clase CommandListener para una descripción completa de los posibles comandos y sus efectos
#
Header  header

string nombre
string param1
string param2
string param3
string param4
int32 param10
int32 param20
int32 param30
int32 param40
