# Define un mensaje completo de acción para el robot
Header  header

int32 modoMotor      # Modo motor
int32 motorIzquierdo # Valor para el motor izquierdo
int32 motorDerecho   # Valor para el motor derecho
int32 r0             # Rojo led 0
int32 g0             # Verde led 0
int32 b0             # Azul led 0
int32 r1
int32 g1
int32 b1
int32 r2
int32 g2
int32 b2
int32 r3
int32 g3
int32 b3
int32 r4
int32 g4
int32 b4
int32 r5
int32 g5
int32 b5
int32 r6
int32 g6
int32 b6
int32 r7
int32 g7
int32 b7
int32 r8
int32 g8
int32 b8
