/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_fic_android_robot_control_camera_AprilTagNdkInterface */

#ifndef _Included_es_udc_fic_android_robot_control_camera_AprilTagNdkInterface
#define _Included_es_udc_fic_android_robot_control_camera_AprilTagNdkInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_udc_fic_android_robot_control_camera_AprilTagNdkInterface
 * Method:    process
 * Signature: ([FII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_es_udc_fic_android_robot_1control_camera_AprilTagNdkInterface_process
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
