# A full action message for the robot
Header  header

# Engine
int32 engineMode
int32 leftEngine
int32 rightEngine

# Leds are represented by 3 values (red, green, blue)
# the robot has 9 of them (the first is number 0)

# Led 0
int32 r0
int32 g0
int32 b0

# Led 1
int32 r1
int32 g1
int32 b1

# Led 2
int32 r2
int32 g2
int32 b2

# Led 3
int32 r3
int32 g3
int32 b3

# Led 4
int32 r4
int32 g4
int32 b4

# Led 5
int32 r5
int32 g5
int32 b5

# Led 6
int32 r6
int32 g6
int32 b6

# Led 7
int32 r7
int32 g7
int32 b7

# Led 8
int32 r8
int32 g8
int32 b8
